### ISSUE TITLE
REQUEST: New membership for yih-wang

### ISSUE THREAD

**Issue by yih-wang** [opendatahub-io/org-management#33]
### GitHub Username

@yih-wang

### Requirements

- [X] I have reviewed the [community membership guidelines](community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined to the [Open Data Hub Slack Workspace](https://odh-io.slack.com/) [Invite Link](https://join.slack.com/t/odh-io/shared_invite/zt-13hp18gxj-Yb34PfQyP9GDmKMU7AkVYw)
- [X] I have subscribed to the [Open Data Hub mailing list](mailto:odh-community@googlegroups.com)
- [X] I am actively contributing to 1 or more Open Data Hub subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS (or CODEOWNERS) file within one of the Open Data Hub GitHub organizations or a member of the steering committee

### Sponsor 1

@kywalker-rh

### Sponsor 2

@simrandhaliw

### List of contributions to the Open Data Hub project

- Responsible for this [issue](https://github.com/opendatahub-io/sig-ml-developer-experience/issues/57) and the following designs for Model Registry

**Comment by LaVLaS** [comment]
@kywalker-rh Thx. Just needed your acknowledgement.  The PR template was designed to alleviate the requirement for someone to fork the repo just to create a PR but there is no automation connected to streamline the workflow
