### ISSUE TITLE
REQUEST: New membership for ralombar

### ISSUE THREAD

**Issue by ralombar** [opendatahub-io/org-management#65]
### GitHub Username

ralombar

### Requirements

- [X] I have reviewed the [community membership guidelines](community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined to the [Open Data Hub Slack Workspace](https://odh-io.slack.com/) [Invite Link](https://join.slack.com/t/odh-io/shared_invite/zt-13hp18gxj-Yb34PfQyP9GDmKMU7AkVYw)
- [X] I have subscribed to the [Open Data Hub mailing list](mailto:odh-community@googlegroups.com)
- [X] I am actively contributing to 1 or more Open Data Hub subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS (or CODEOWNERS) file within one of the Open Data Hub GitHub organizations or a member of the steering committee

### Sponsor 1

kywalker-rh

### Sponsor 2

vconzola

### List of contributions to the Open Data Hub project

First task: Admin UI configuration and settings  (https://issues.redhat.com/browse/RHODS-6964)

**Comment by accorvin** [comment]
@ralombar can you open a pull request adding yourself to the [list of members](https://github.com/opendatahub-io/org-management/blob/main/config/opendatahub-io/org.yaml#L16). This request seems good to me.

**Comment by ralombar** [comment]
This pull request should be done now! Thank you.

**Comment by andrewballantyne** [comment]
This appears done. I'm also adding you to the UX team on @kywalker-rh's request

https://github.com/opendatahub-io/org-management/pull/142

@anishasthana can you close this ticket?

**Comment by anishasthana** [comment]
Done!
